# Generated by Django 4.2.8 on 2024-12-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0018_jornalista_show_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornalista',
            name='foto_do_curriculo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
