# Generated by Django 4.2.8 on 2024-12-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0019_jornalista_foto_do_curriculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornalista',
            name='foto_do_curriculo',
        ),
    ]
